<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title><?=$v($title)?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="title" content="<?=$v($title)?>">
    <meta name="description" content="<?=$v($description)?>">
    <meta name="language" content="English">
    <meta name="author" content="asvvvad">
    <link rel="stylesheet" href="<?=$v($_ENV['CSS'])?>/light.min.css">
    <link rel="stylesheet" href="<?=$v($_ENV['CSS'])?>/mono-color.min.css">
</head>

<body>
    <?=$v->section('content')?>
</body>

</html>